# Uncomment this line to define a global platform for your project
platform :ios, '7.1'

target 'letshake' do
pod 'SDWebImage'
pod 'HTProgressHUD'
pod 'AFNetworking'
pod 'UICountingLabel'
pod 'Google/Analytics'
end